### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by nischa564** [sdsc-bw/DataFactory#16]
When I run in [04_Finetuning.ipynb](https://github.com/sdsc-bw/DataFactory/blob/develop/demos/04_Finetuning.ipynb) the computer vision finetuning on GPU, I am running out of memory after a few evaluations:

`job exception: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 2.93 GiB already allocated; 0 bytes free; 2.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

However, I am cleaning the cache before every model training with:
`torch.cuda.empty_cache()
 gc.collect()`

Has anyone a solution for this?

**Comment by riedel** [comment]
Anything that is the result of a notebook cell with actually keep a pointer as you can access cells using _.  gc.collect is thus not really well working in jupyter.

have you tried to run the same code without jupyter? 

Have you also tried torch.cuda.ipc_collect() ?

**Comment by riedel** [comment]
Other people have similar problems btw: https://github.com/pytorch/pytorch/issues/67680

**Comment by nischa564** [comment]
Thank you. The problem seems to be solved by using fastai for training.
